In [3]:
import torch

In [4]:
torch.cuda.is_available()

True

## Calc a NN

In [2]:
def activation(x):

    return 1/(1+torch.exp(-x))

In [3]:
torch.manual_seed(seed = 7)

features = torch.randn((1,5))
weights = torch.randn_like(features)

bias = torch.randn((1,1))

In [4]:
features.T

tensor([[-0.1468],
        [ 0.7861],
        [ 0.9468],
        [-1.1143],
        [ 1.6908]])

In [5]:
weights

tensor([[-0.8948, -0.3556,  1.2324,  0.1382, -1.6822]])

In [6]:
bias

tensor([[0.3177]])

In [7]:
yhat = activation(torch.sum(weights*features)+bias)
yhat

tensor([[0.1595]])

In [8]:
activation(torch.mm(weights, features.T)+bias)

tensor([[0.1595]])

## Useful functions

In [9]:
weights

tensor([[-0.8948, -0.3556,  1.2324,  0.1382, -1.6822]])

In [10]:
weights.resize(5,1)

c:\UserData\z635177\Udacity_Kurse\Udacity_MachineLearning_Class\environment\.venv\Lib\site-packages\torch\_tensor.py:889: UserWarning: non-inplace resize is deprecated
  warnings.warn("non-inplace resize is deprecated")


tensor([[-0.8948],
        [-0.3556],
        [ 1.2324],
        [ 0.1382],
        [-1.6822]])

In [11]:
weights.reshape(shape = (5,1))

tensor([[-0.8948],
        [-0.3556],
        [ 1.2324],
        [ 0.1382],
        [-1.6822]])

## Networks Using Matrix Multiplication

In [59]:
 def activation(x):

    return 1/(1+torch.exp(-x))

In [67]:
torch.manual_seed(7)

features = torch.randn((1,3))

n_input = features.shape[1]
n_hidden = 2
n_output = 1

W1 = torch.randn(n_input, n_hidden)
W2 = torch.randn(n_hidden, n_output)

B1 = torch.randn((1, n_hidden))
B2 = torch.randn((1, n_output))

In [68]:
features, W1

(tensor([[-0.1468,  0.7861,  0.9468]]),
 tensor([[-1.1143,  1.6908],
         [-0.8948, -0.3556],
         [ 1.2324,  0.1382]]))

In [69]:
features.shape, W1.shape

(torch.Size([1, 3]), torch.Size([3, 2]))

In [70]:
torch.mm(features, W1)+B1

tensor([[ 0.7598, -0.2596]])

In [71]:
hidden = activation(torch.mm(features, W1)+B1)
output = activation(torch.mm(hidden, W2)+ B2)
print(output)

tensor([[0.3171]])


## Transform from numpy and back

In [78]:
import numpy as np 

a = np.random.rand(4,3)
a

array([[0.79570367, 0.41426532, 0.72501857],
       [0.4720041 , 0.31216078, 0.68962964],
       [0.3429574 , 0.64368048, 0.84764375],
       [0.79191047, 0.29127149, 0.3250528 ]])

In [79]:
b = torch.from_numpy(4)


RuntimeError: Numpy is not available